import { wordAndTranslate } from "./types"

// export const wordArray: wordAndTranslate[] = [
//     { word: "the", translate: "o, a" },
//     { word: "be", translate: "ser, estar" },
//     { word: "to", translate: "para, por, até" },
//     { word: "of", translate: "de" },
//     { word: "and", translate: "e" },
//     { word: "a", translate: "um, uma" },
//     { word: "in", translate: "em, dentro de" },
//     { word: "that", translate: "que, aquele, aquela" },
//     { word: "have", translate: "ter" },
//     { word: "I", translate: "eu" },
// ]

export const wordArray: wordAndTranslate[] = [
    { word: "the", translate: "o/a/os/as" },
  { word: "be", translate: "ser/estar" },
  { word: "to", translate: "para/a" },
  { word: "of", translate: "de" },
  { word: "and", translate: "e" },
  { word: "a", translate: "um/uma" },
  { word: "in", translate: "em" },
  { word: "that", translate: "que/aquele" },
  { word: "have", translate: "ter" },
  { word: "I", translate: "eu" },
  { word: "it", translate: "isso/ele/ela" },
  { word: "for", translate: "para/por" },
  { word: "not", translate: "não" },
  { word: "on", translate: "em/sobre" },
  { word: "with", translate: "com" },
  { word: "he", translate: "ele" },
  { word: "as", translate: "como" },
  { word: "you", translate: "você" },
  { word: "do", translate: "fazer" },
  { word: "at", translate: "em/para" },
  { word: "this", translate: "este/esta" },
  { word: "but", translate: "mas" },
  { word: "his", translate: "dele" },
  { word: "by", translate: "por" },
  { word: "from", translate: "de/desde" },
  { word: "they", translate: "eles/elas" },
  { word: "we", translate: "nós" },
  { word: "say", translate: "dizer" },
  { word: "her", translate: "dela" },
  { word: "she", translate: "ela" },
  { word: "or", translate: "ou" },
  { word: "an", translate: "um/uma" },
  { word: "will", translate: "vai/vão (futuro)" },
  { word: "my", translate: "meu/minha" },
  { word: "one", translate: "um/uma" },
  { word: "all", translate: "todos/todas" },
  { word: "would", translate: "iria/eria (condicional)" },
  { word: "there", translate: "lá/ali" },
  { word: "their", translate: "deles/delas" },
  { word: "what", translate: "o que" },
  { word: "so", translate: "então/tão" },
  { word: "up", translate: "para cima" },
  { word: "out", translate: "fora" },
  { word: "if", translate: "se" },
  { word: "about", translate: "sobre" },
  { word: "who", translate: "quem" },
  { word: "get", translate: "obter/conseguir" },
  { word: "which", translate: "qual/quais" },
  { word: "go", translate: "ir" },
  { word: "me", translate: "me/mim" },
  { word: "when", translate: "quando" },
  { word: "make", translate: "fazer" },
  { word: "can", translate: "poder" },
  { word: "like", translate: "gostar/como" },
  { word: "time", translate: "tempo/hora" },
  { word: "no", translate: "não" },
  { word: "just", translate: "apenas" },
  { word: "him", translate: "ele" },
  { word: "know", translate: "saber/conhecer" },
  { word: "take", translate: "pegar/tomar" },
  { word: "people", translate: "pessoas" },
  { word: "into", translate: "para dentro" },
  { word: "year", translate: "ano" },
  { word: "your", translate: "seu/sua" },
  { word: "good", translate: "bom/boa" },
  { word: "some", translate: "alguns/algumas" },
  { word: "could", translate: "poderia" },
  { word: "them", translate: "eles/elas" },
  { word: "see", translate: "ver" },
  { word: "other", translate: "outro/outra" },
  { word: "than", translate: "do que" },
  { word: "then", translate: "então" },
  { word: "now", translate: "agora" },
  { word: "look", translate: "olhar" },
  { word: "only", translate: "apenas" },
  { word: "come", translate: "vir" },
  { word: "its", translate: "dele/dela (coisas)" },
  { word: "over", translate: "sobre/acima" },
  { word: "think", translate: "pensar" },
  { word: "also", translate: "também" },
  { word: "back", translate: "costas/voltar" },
  { word: "after", translate: "depois" },
  { word: "use", translate: "usar" },
  { word: "two", translate: "dois/duas" },
  { word: "how", translate: "como" },
  { word: "our", translate: "nosso/nossa" },
  { word: "work", translate: "trabalho/trabalhar" },
  { word: "first", translate: "primeiro" },
  { word: "well", translate: "bem" },
  { word: "way", translate: "caminho/maneira" },
  { word: "even", translate: "mesmo/até" },
  { word: "new", translate: "novo" },
  { word: "want", translate: "querer" },
  { word: "because", translate: "porque" },
  { word: "any", translate: "qualquer" },
  { word: "these", translate: "estes/estas" },
  { word: "give", translate: "dar" },
  { word: "day", translate: "dia" },
  { word: "most", translate: "mais" },
  { word: "us", translate: "nós" }
]